# Generated by Django 4.0.3 on 2022-06-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('imagen', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('dinero', models.FloatField()),
                ('contraseña', models.CharField(max_length=10)),
                ('total', models.FloatField(default=0)),
                ('correo', models.EmailField(max_length=254)),
                ('clientes', models.ManyToManyField(to='tienda.producto')),
            ],
        ),
    ]
